### PR TITLE
Fixes#16(Made corrections in Readme)

### PR DESCRIPTION
**Pull request by Archies11**
I have fixed the errors I could find.

### CODE REVIEW

**Review by sansyrox — CHANGES_REQUESTED** [review]
Your PR still contains the commits in which package-lock.json was removed. Please fix the commit order.
Rest looks good

**Comment by Archies11** [comment]
How do i fix the commit order?Is there a link that might help me?

**Comment by sansyrox** [comment]
@Archies11 , you can have a look here https://stackoverflow.com/questions/35846154/git-rebase-interactive-drop-vs-deleting-the-commit-line

**Comment by sansyrox** [comment]
Closed as not relevant anymore.

**Pull request closed without merging**
